const projects = [
    {
        id: 1,
        name: "Official War Brokers Stats",
        creator: "Rocky",
        category: "WB Stats Sites",
        shortDescription: "The original community stats site for War Brokers — daily and all-time leaderboards, player profiles, ribbons, medals, and squad pages.",
        details: "Built by Rocky with collaboration from the War Brokers devs. Features daily top 30 rankings by kills, vehicle kills, and longest kills, plus lifetime top 10 stats, squad rankings, and player profiles with customizable themes. The site queries the WB game database directly, but its backend schema is frozen at the weapon list from when Rocky left — newer weapons added to the game are not reflected. Still live and usable for older stats.",
        image: "images/stats.warbrokers.io.jpg",
        link: "https://stats.warbrokers.io/",
        status: "Maintenance"
    },
    {
        id: 2,
        name: "WB Stats (POMP)",
        creator: "POMP",
        category: "WB Stats Sites",
        shortDescription: "An improved community stats site with ELO rankings, global leaderboards, and a modern interface — left in alpha state.",
        details: "Built by POMP as part of the War Brokers Projects monorepo, intended as a full replacement for the original stats site. Features Kills ELO, Games ELO, and XP/Level leaderboards. Development was halted mid-way and the project has been in an incomplete alpha state for several years. Data is sourced from WBAPI.",
        image: "images/stats.wbpjs.com.jpg",
        link: "https://stats.wbpjs.com/",
        status: "Maintenance"
    },
    {
        id: 3,
        name: "WB Timeline",
        creator: "War Brokers Projects",
        category: "WB Community Sites",
        shortDescription: "A chronological record of significant events and milestones in the War Brokers community history.",
        details: "Interactive timeline website showcasing major community events, game updates, tournament results, and historical moments in War Brokers. Built by POMP as part of the War Brokers Projects monorepo. Listed as the most stable project in the WBP suite. Helps players understand the game's evolution and community culture over time. The project was never finished and stopped updated by 2021, but still serves as a useful historical archive.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=War-Brokers&repo=War-Brokers&theme=dark&hide_border=true",
        link: "https://wbtimeline.wbpjs.com/",
        status: "Maintenance"
    },
    {
        id: 18,
        name: "WB Stats Bot",
        creator: "DarkPassenger",
        category: "WB Discord Bots",
        shortDescription: "A feature-rich Discord bot for War Brokers stats including player lookups, squad stats, and daily snapshot tracking.",
        details: "A Discord bot by DarkPassenger that extends beyond SquadBot's capabilities. Features include player stat lookups, squad statistics (powered by SquadLink API for squad info), and daily snapshot tracking to show stat progression over time. One of the more comprehensive WB Discord bots available.",
        image: "images/wbstatsbot.jpg",
        link: null,
        status: "Active"
    },
    {
        id: 20,
        name: "SquadLink Bot",
        creator: "Projelly",
        category: "WB Discord Bots",
        shortDescription: "A Discord bot by Projelly showing rich squad information with interactive UI and graphs, powered by SquadLink API.",
        details: "A Discord bot created by Projelly that surfaces all squad-related data from the SquadLink API. Features a rich interactive UI and embeds, including interactive graphs. Pairs with the SquadLink Graphs web page (squadlink-dev.github.io/squadlink-graphs) which renders interactive player and squad graphs in the browser using data from ZorkaA's playerdb.csv dataset.",
        image: "images/squadlinkbot.jpg",
        link: null,
        status: "Active"
    },
    {
        id: 4,
        name: "SquadBot",
        creator: "DaVince",
        category: "WB Discord Bots",
        shortDescription: "Discord bot connecting players to War Brokers stats with slash commands for player stats, squad info, and K/D tracking.",
        details: "A Discord bot serving as a quick bridge between Discord and War Brokers. Commands include player stat lookups, K/D ratio progress, squad statistics, and a topic generator. Uses slash commands for easy access to player information directly within Discord. Pulls data from the War Brokers stats ecosystem.",
        image: "images/squadbot.jpg",
        link: "https://top.gg/bot/725779812412817429",
        status: "Maintenance"
    },
    {
        id: 5,
        name: "msfish",
        creator: "ddupas",
        category: "WB Discord Bots",
        shortDescription: "Private squad-specific stats bot for War Fish squad with time-series charts and medal tracking.",
        details: "A specialized Discord bot built for the War Fish WB squad. Periodically collects player statistics from stats.warbrokers.io, stores them in SQLite, and provides time-series charts via a public website. Users can query medals and activity stats directly in Discord. Built with Node.js and Discord.js. Squad-specific and not publicly available.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=ddupas&repo=msfish&theme=dark&hide_border=true",
        link: "https://github.com/ddupas/msfish",
        status: "Removed"
    },
    {
        id: 17,
        name: "[APG] Bot",
        creator: "[APG] Did You Get Sniped?",
        category: "WB Discord Bots",
        shortDescription: "The official [APG] squad Discord bot with reaction roles, purge commands, and APG-related content.",
        details: "A squad-specific Discord bot built for the [APG] War Brokers community. Includes reaction roles, a purge command, APG-related images, and general server management features. Not a general-purpose WB stats bot — primarily useful within the [APG] Discord. Listed on Top.gg but appears inactive.",
        image: "images/apg_bot.jpg",
        link: "https://top.gg/bot/933820741915385906",
        status: "Removed"
    },
    {
        id: 6,
        name: "WB API",
        creator: "POMP",
        category: "WB APIs & Endpoints",
        shortDescription: "The most accurate public API for War Brokers data — player stats, ELO rankings, squad members, and server status.",
        details: "Created by POMP and hosted on his own server in Seoul, South Korea. Acts as a database mirror and API proxy for the WB game database, backed by a PostgreSQL instance on Supabase (AWS, California). Exposes endpoints for player lookup by UID or name, ELO percentile rankings, squad member lists, server status, and player counts. Full source code is available in the War Brokers Projects monorepo. Currently in maintenance-only mode — no new features, but kept running.",
        image: "images/wbapi.wbpjs.com.jpg",
        link: "https://wbapi.wbpjs.com/api-docs/#/",
        status: "Maintenance"
    },
    {
        id: 7,
        name: "WB Types",
        creator: "War Brokers Projects",
        category: "WB APIs & Endpoints",
        shortDescription: "Shared TypeScript types and Zod validation schemas for all War Brokers data structures.",
        details: "A library providing consistent TypeScript type definitions and Zod validation schemas for War Brokers data, including player stats, weapon kill maps, squad data, and game mode results. Part of the War Brokers Projects monorepo. Used internally by WBAPI and the stats site, and useful for any developer building tools that interact with WB data.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=War-Brokers&repo=War-Brokers&theme=dark&hide_border=true",
        link: "https://github.com/War-Brokers/War-Brokers/tree/master/libs/wb-types",
        status: "Maintenance"
    },
    {
        id: 8,
        name: "WB UI v2",
        creator: "War Brokers Projects",
        category: "WB Tools & Utilities",
        shortDescription: "An ambitious community redesign of the War Brokers in-game UI, built in C#/Unity.",
        details: "A pre-alpha reimagining of the War Brokers in-game user interface by the WBP team. Built with C# and Unity to explore modern interaction patterns and visual improvements while maintaining compatibility with the game. Development stalled and the project has not been updated in years.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=War-Brokers&repo=wbuiv2&theme=dark&hide_border=true",
        link: "https://github.com/War-Brokers/wbuiv2",
        status: "Maintenance"
    },
    {
        id: 9,
        name: "War Brokers Mods (WBM)",
        creator: "developomp",
        category: "WB Mods",
        shortDescription: "An unofficial browser extension mod for War Brokers adding in-game overlays, ELO display, and quality-of-life improvements.",
        details: "A community-created browser extension mod that ran inside the warbrokers.io page context. Added an in-game overlay showing live ELO, kill counts, and other stats pulled from WBAPI. Built by developomp and at one point officially acknowledged by the WB devs. The mod and its companion OBS overlays project (WBM-Overlays) are now archived. The repository is private/archived.",
        image: null,
        link: "https://github.com/War-Brokers-Mods/WBM",
        status: "Removed"
    },
    {
        id: 10,
        name: "War Brokers Wiki",
        creator: "Community",
        category: "WB Community Sites",
        shortDescription: "Comprehensive community encyclopedia covering maps, weapons, vehicles, game modes, items, and strategy guides.",
        details: "Player-maintained wiki on Fandom with extensive documentation of all game content. Includes beginner guides, weapon statistics, map information, vehicle details, cosmetics catalog, mission guides, advanced strategy articles, and a full history of game events. The most thorough written reference for War Brokers.",
        image: "images/war-brokers.fandom.com.jpg",
        link: "https://war-brokers.fandom.com/wiki/War_Brokers_Wiki",
        status: "Active"
    },
    {
        id: 11,
        name: "PCGamingWiki — War Brokers",
        creator: "Community",
        category: "WB Community Sites",
        shortDescription: "Community-driven resource for troubleshooting bugs, crashes, and performance optimization for War Brokers on PC.",
        details: "The PCGamingWiki page for War Brokers documents known bugs, workarounds, graphics settings, keybindings, and performance tweaks. Useful for players running the Steam version or experiencing technical issues with the browser version.",
        image: "images/pcgamingwiki.com.jpg",
        link: "https://www.pcgamingwiki.com/wiki/War_Brokers",
        status: "Maintenance"
    },
    {
        id: 12,
        name: "War Brokers Projects (WBP)",
        creator: "POMP",
        category: "WB Community Sites",
        shortDescription: "The GitHub organization and monorepo housing WBAPI, the improved stats site, WB Timeline, WB Types, and WBM.",
        details: "The central GitHub organization created by POMP to consolidate all War Brokers community tooling. The public monorepo contains the full source for WBAPI, the stats site frontend, WB Timeline, and the WB Types library. Serves as the backbone of the community developer ecosystem. Currently in maintenance-only mode.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=War-Brokers&repo=War-Brokers&theme=dark&hide_border=true",
        link: "https://github.com/War-Brokers",
        status: "Maintenance"
    },
    {
        id: 13,
        name: "WB Info (Did You Get Sniped?)",
        creator: "[APG] Did You Get Sniped?",
        category: "WB Stats Sites",
        shortDescription: "A lightweight player stat lookup tool with ELO rankings and a direct link to the player's full stats page.",
        details: "A simple single-page stat lookup tool built by [APG] Did You Get Sniped?. Allows players to search by name or UID and get a quick overview of their stats and ELO, with a direct link to their full stats.warbrokers.io profile. Credits POMP's WBAPI and EpicEfeathers.",
        image: "images/didyougetsniped.github.io.jpg",
        link: "https://didyougetsniped.github.io/wbinfo",
        status: "Active"
    },
    {
        id: 14,
        name: "WB Utilities",
        creator: "ZorkaA",
        category: "WB Tools & Utilities",
        shortDescription: "A collection of analytical and visualization tools for War Brokers — player count graphs, squad stats, item viewer, matchmaking demos, and more.",
        details: "A GitHub Pages site by ZorkaA hosting multiple WB utility tools: an online player count visualization, time-series squad player count tracking, an in-game item viewer, last-seen tracker for squad members, general squad stats viewer, and a Monte Carlo matchmaking balancing demo. Several tools are still WIP including historical analytics and predictive stats modeling. Pulls data from POMP's WBAPI.",
        image: "images/zorkaa.github.io.jpg",
        link: "https://zorkaa.github.io/wb/",
        status: "Active"
    },
    {
        id: 15,
        name: "wbdb",
        creator: "ZorkaA",
        category: "WB Tools & Utilities",
        shortDescription: "A Python/Jupyter script that pulls all squad member IDs from the stats site and fetches full player data via WBAPI, optimized for Google Colab.",
        details: "A data collection script by ZorkaA that scrapes squad member IDs from stats.warbrokers.io, then uses POMP's WBAPI to pull detailed player data for each member. Outputs a CSV with roughly 1000 rows of player data (as of Nov 2023). Designed to run in Google Colab with Google Drive integration. Includes a caution against abuse due to lack of built-in rate limiting.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=ZorkaA&repo=wbdb&theme=dark&hide_border=true",
        link: "https://github.com/ZorkaA/wbdb",
        status: "Active"
    },
    {
        id: 16,
        name: "WarBrokers Localization",
        creator: "TrebuchetEntertainmentLLC / ZorkaA",
        category: "WB Tools & Utilities",
        shortDescription: "The official community-maintained localization files for War Brokers, covering 13+ languages.",
        details: "The official localization repository for warbrokers.io, originally created by Trebuchet Entertainment LLC (the WB devs) and forked/contributed to by the community. Contains CSV translation files for English, German, Spanish, French, Italian, Japanese, Korean, Dutch, Portuguese, Russian, Swedish, Turkish, and Chinese. Community members can submit new translations or fix existing ones by editing the CSV files.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=TrebuchetEntertainmentLLC&repo=WarBrokersLocalization&theme=dark&hide_border=true",
        link: "https://github.com/TrebuchetEntertainmentLLC/WarBrokersLocalization",
        status: "Active"
    },
    {
        id: 19,
        name: "SquadLink API",
        creator: "Projelly",
        category: "WB APIs & Endpoints",
        shortDescription: "A rich squad analytics API that performs weekly data processing across all squads using WBAPI as its data source.",
        details: "Built by Projelly and hosted on Render. Provides rich squad-level information by performing massive data calculations and cleanup on a weekly basis, pulling all underlying data from POMP's WBAPI. Exposes aggregated squad analytics not available directly from WBAPI. Documented via Swagger UI. Powers the WB Stats Bot and SquadLink Bot.",
        image: "images/squadlinkapi.jpg",
        link: "https://squadlinkapi.onrender.com/docs",
        status: "Active"
    },
    {
        id: 21,
        name: "WB Squad List Numbers",
        creator: "Encryp7R",
        category: "WB Tools & Utilities",
        shortDescription: "A Python script that generates a dictionary of all WB squad names and their player counts by scraping the stats site.",
        details: "A small Python utility by Encryp7R that scrapes stats.warbrokers.io to build a complete dictionary mapping every squad name to its member count. Uses the requests, BeautifulSoup4, and tqdm libraries. Intended for recreational/research use. Mentioned in ZorkaA's wbdb README as an easier alternative for counting squad members.",
        image: "https://github-readme-stats.vercel.app/api/pin/?username=Encryp7R&repo=WB-Squad-List-Numbers&theme=dark&hide_border=true",
        link: "https://github.com/Encryp7R/WB-Squad-List-Numbers",
        status: "Maintenance"
    }
];